USE QLDT2
GO

BULK INSERT KHOA
FROM 'D:\CSDL\BTL\DataBase\KHOA.csv'
WITH (
    FIELDTERMINATOR = ',',  
    ROWTERMINATOR = '\n',
    FIRSTROW = 2,  --Bỏ qua dòng đầu tiên
	CODEPAGE = '65001'  -- Sử dụng CODEPAGE để chỉ định mã hóa UTF-8
)


BULK INSERT CHUONGTRINHDAOTAO
FROM 'D:\CSDL\BTL\DataBase\CHUONGTRINHDAOTAO.csv'
WITH (
    FIELDTERMINATOR = ',',  
    ROWTERMINATOR = '\n',
    FIRSTROW = 2,
	CODEPAGE = '65001'
)

BULK INSERT LOPCHINHQUY
FROM 'D:\CSDL\BTL\DataBase\LOPCHINHQUY.csv'
WITH (
	FIELDTERMINATOR = ',',
	ROWTERMINATOR = '\n',
	FIRSTROW = 2,
	CODEPAGE = '65001'
)

BULK INSERT DOITUONG
FROM 'D:\CSDL\BTL\DataBase\DOITUONG.csv'
WITH (
	FIELDTERMINATOR = ',',
	ROWTERMINATOR = '\n',
	FIRSTROW = 2,
	CODEPAGE = '65001'
)

BULK INSERT SINHVIEN
FROM 'D:\CSDL\BTL\DataBase\SINHVIEN.csv'
WITH (
	FIELDTERMINATOR = ',',
	ROWTERMINATOR = '\n',
	FIRSTROW = 2,
	CODEPAGE = '65001'
)

BULK INSERT GIANGVIEN
FROM 'D:\CSDL\BTL\DataBase\GIANGVIEN.csv'
WITH (
	FIELDTERMINATOR = ',',
	ROWTERMINATOR = '\n',
	FIRSTROW = 2,
	CODEPAGE = '65001'
)

BULK INSERT MONHOC
FROM 'D:\CSDL\BTL\DataBase\MONHOC.csv'
WITH (
	FIELDTERMINATOR = ',',
	ROWTERMINATOR = '\n',
	FIRSTROW = 2,
	CODEPAGE = '65001'
)

BULK INSERT LOPTINCHI
FROM 'D:\CSDL\BTL\DataBase\LOPTINCHI.csv'
WITH (
	FIELDTERMINATOR = ',',
	ROWTERMINATOR = '\n',
	FIRSTROW = 2,
	CODEPAGE = '65001'
)

BULK INSERT TIETHOC
FROM 'D:\CSDL\BTL\DataBase\TIETHOC.csv'
WITH (
	FIELDTERMINATOR = ',',
	ROWTERMINATOR = '\n',
	FIRSTROW = 2,
	CODEPAGE = '65001'
)

BULK INSERT HOADON
FROM 'D:\CSDL\BTL\DataBase\HOADON.csv'
WITH (
	FIELDTERMINATOR = ',',
	ROWTERMINATOR = '\n',
	FIRSTROW = 2,
	CODEPAGE = '65001'
)

BULK INSERT HOCBONG
FROM 'D:\CSDL\BTL\DataBase\HOCBONG.csv'
WITH (
	FIELDTERMINATOR = ',',
	ROWTERMINATOR = '\n',
	FIRSTROW = 2,
	CODEPAGE = '65001'
)

BULK INSERT DOITUONG_SDT
FROM 'D:\CSDL\BTL\DataBase\DOITUONG_SDT.csv'
WITH (
	FIELDTERMINATOR = ',',
	ROWTERMINATOR = '\n',
	FIRSTROW = 2,
	CODEPAGE = '65001'
)

BULK INSERT GIANGVIEN_BANGCAP
FROM 'D:\CSDL\BTL\DataBase\GIANGVIEN_BANGCAP.csv'
WITH (
	FIELDTERMINATOR = ',',
	ROWTERMINATOR = '\n',
	FIRSTROW = 2,
	CODEPAGE = '65001'
)

BULK INSERT CHUONGTRINH_MONHOC
FROM 'D:\CSDL\BTL\DataBase\CHUONGTRINH_MONHOC.csv'
WITH (
	FIELDTERMINATOR = ',',
	ROWTERMINATOR = '\n',
	FIRSTROW = 2,
	CODEPAGE = '65001'
)


